namespace WiiU.Core.Models;

public static class Constants
{

    public static readonly byte[] WiiUCommonKey =
    [
        0xD7, 0xB0, 0x04, 0x02, 0x65, 0x9B, 0xA2, 0xAB,
        0xD2, 0xCB, 0x0D, 0xB2, 0x7F, 0xA2, 0xB6, 0x56
    ];

    public const string TicketTemplateBase64 =
        "AAEABNFepe0Vq+Ea0V6l7RWr4RrRXqXtFavhGtFepe0Vq+Ea0V6l7RWr4RrRXqXtFavhGtFepe0Vq+Ea0V6l7RWr4RrRXqXtFavh" +
        "GtFepe0Vq+Ea0V6l7RWr4RrRXqXtFavhGtFepe0Vq+Ea0V6l7RWr4RrRXqXtFavhGtFepe0Vq+Ea0V6l7RWr4RrRXqXtFavhGtFe" +
        "pe0Vq+Ea0V6l7RWr4RrRXqXtFavhGtFepe0Vq+Ea0V6l7RWr4RrRXqXtFavhGtFepe0Vq+Ea0V6l7RWr4RrRXqXtFavhGtFepe0V" +
        "q+Ea0V6l7RWr4RrRXqXtFavhGtFepe0Vq+Ea0V6l7RWr4RoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAABSb290LUNBMDAwMDAwMDMtWFMwMDAwMDAwYwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAA/u36zv7t+s7+7frO/u36zv7t+s7+7frO/u36zv7t+s7+7frO/u36zv7t+s7+7frO/u36zv7t+s7+7frOAQAAwpNX" +
        "UV+9uEuYIRRPtEjLqAAAAAAAAAAAAAAAAAAABQAAEBeSAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAABABQAAACsAAAAFAABABQAAAAAAAAAKAAAAAEAAACEAAAAhAADAAAAAAAA////////////////////////////////////////" +
        "//8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=";

    public const string CertTemplateBase64 =
        "AAEABC6mbGbP8zV5fQSXt3oZf5/lGrWkE3Xcc/2eCxBmmxuaW36Kso8BtntiVMFKoTMUGPJbpUkATDeN1y8M5jsfcJGq/jgJt6xs" +
        "KHamHWBRbEOmNykWLSgL4hvo4v4FfY624gQkIkVzGrb+4w5TNTc+66lw1TG7ossiLZaEOH1fKhv3UgDOBlbjkM4ZE1tZ4U8PpcEo" +
        "GnOGzNHI7D+tcPvOdN7uH9BfRjMLUfm3nh3b9OM/FIidBSgpJMX13Cdm7wYn1+7cc25nwuW5ODRmgHIhbRx4uCOgctNP8+z5vRGi" +
        "mvFsM70Jr7LXTVNOAnwZJA1ZWmjrswWsxEqzirggxtQmVgwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAABSb290LUNBMDAwMDAwMDMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAUNQMDAwMDAwMGIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAATeggLponFkP0LLw1PVrYy+5NO0HOVF7M6ed4EDuktwx03x/c78EvT5E4gq1pv6vWYTMH2Bi6an+VsMoXcbyXd1dC/n+Lv6DXf" +
        "JjTtk3+rAhTRBICc90uGDmsEg/TNLasqlgK8VvDWvZRq7W4L5PCPJmhr0J732zJfgrGPavLtUlv9gotlP+5uzkANWkj/4i1Ti7Uz" +
        "W0FTNC1DNaz1kNDTCuIEPH9a0hT8nA/m+kClyGUGymNpvO5Eoy2eaVzwC0/XmttWjRScICihTJ1xuFDKNls39wtld5H8XXKMThj9" +
        "IlV8QGLXR3FTPHAXnT2uj5KxF+RcszLzs8KiLnBc/sZvbaN3KwABAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAEAA3BBOO+7vaFqmH3ZATJtHJRZSEyIooYbkaMSWHrnDvYjfsUOEDLcOd3ompao6FnXapim5+Nq" +
        "DP41LKiTBYI0/4M/yzsDgR6fDcDZpS+ARbSy+UEbZ6UcRLXvjOd71tVrp1c0oYVt5tS+1tOiQsfIeRs0IjdeXHeavwcvdpXvoPdb" +
        "y4N4n8MOP+TMg5IgeEBjiUnH9ohWX2SbdNY9jVj/rdpXHpVUQmsTGPxGiYPUyKViiwa2/F1QfBPnoYrBUR621i6lRI+DUBRHqa+z" +
        "7MKQPJ3VL5Iqyazb71jGAhhI2W4ghzLT0dnZ6kQNkWIcepnbiEPFnB8uLH2bV31RLBZtb34arUp3SjdEfnj+ICHhSpXREqBoraAZ" +
        "9GPHpVaFqrtoiLkkZIPRi5yAb0dJGDMXgjRKS4UxM0smMDJj2dLrT0u5lgKzUvauQEbGml5+jkoY75vAot7WExBBcBL9gkzBFs+3" +
        "xMH37HF3oXRGy96W8+3Yj80FLwuIikX9rytjE1T0DRbl+pwsTtqY55jRXmBG3FNj8wlrLGB6nY3VWxUCpqx9PMjYxXWZjn15aRDI" +
        "BMSVI1BX6R7NJjfJwYRRUaxrmgSQrj7G9HdAoNsLo20HWVbO5zVOo+mk8nILJlUMfTlDJLwMt+kxfYqGYfQhkf8QsIJWzj/SW3Re" +
        "UZSQa01hy0wuAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUm9vdAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFDQTAwMDAwMDAzAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAe+jvbLJ5yeLu4SHG6vRP9jn4jweLS3ft" +
        "n5VgsDWCgbUOVatyERWhd3A8ejD+OunvHGC8HZdGdrI6aMwEsZhSW8lo8R3i21Dk2efwceVi2uIJIjPp02P2HdfBn/OkqR6PZVPU" +
        "cd17hLnxuM5zNfD1VAVjoeq4OWPgm+kBAR+ZVGNhKHAg6cwNq0h/FA1mJqGDbScRHyBo3kdyFJFRz2nGG6YO+dlJoPcfVJny05rS" +
        "jHAFNIKTxDH/vTP2vKYNxxleorzFbSALr20G0JxB243pxyAVTKSDK2nAjGnNOwc6AGNgL0YtM4BhpepskVzVYjV5w+tkzkTvWG0U" +
        "uqqINAGbPuvu03kAAQABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAASRnr5G" +
        "StD1Us0bcueISRDPVanwLlB4lkHYlmg9wAW9CuqHB52KwoTGdQZfdMi/N8iARECVAqAimAu4rUg4P20op53jlibMsrIqDxnkEDLw" +
        "lLOf8BMxRt7I9sGp1VzSjZ4cR7PRH09UJsLHgBNaJ3XTymebx+g08OD7WOaIYKcTMPyVeReTyPupNaemkI8ine4qDKa5sjsS1JWm" +
        "/hnQ1yZIIWh4YFpmU42/N2iZkF00RfxccnoOE+DiyJccnPpsYGeIdXMqTnVSPS9WLxKqvRVzvwbJQFSu+oGnFBevmkoGbQ/8WtZL" +
        "qyix/2BmH0Q31J4eDZQS60vKz0z9ajQIhHmCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAUm9vdC1DQTAwMDAwMDAzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAFYUzAwMDAwMDBjAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE3oIlK1Q" +
        "W7bGfi5b3Wo77EPZEMdy6cwpDaWFiLd9zBFoC7Pin06ruybpjCYBmFwEG7FDeOaJGBqtdwVo6SiiuYFn7j4Q0HK+7x+iL6KqPhPx" +
        "Hhg2qSpCge9wqvTkYpmCIcb7ub3QF+asWQSU6c6phZzrLSpMF2bywzkSxY8UqAPjb8zczNwT/XrnfHp42ZfmrMNVV+DT6etktDyS" +
        "9MUNZ6YC3rORsGZhzTKIC9ZJEq8cvLcWKgbwJWXTsOzk/OzdropJNNuO5n8wF5hiIRVdExxsPwmrGUXCBqxwyUKzb0mhGDvNeLbk" +
        "tHxsXKwPjWL4l8aVPdEvKLcMW333UYGamDRlJiUAAQABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAA==";
}